"""fix slug field to recipe

Revision ID: 59b55de9827f
Revises: f9d05eb47ce9
Create Date: 2026-02-12 01:32:31.930517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59b55de9827f'
down_revision: Union[str, Sequence[str], None] = 'f9d05eb47ce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('slug', sa.String(), nullable=False))
    op.drop_index(op.f('ix_recipes_slub'), table_name='recipes')
    op.create_index(op.f('ix_recipes_slug'), 'recipes', ['slug'], unique=True)
    op.drop_column('recipes', 'slub')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('slub', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_recipes_slug'), table_name='recipes')
    op.create_index(op.f('ix_recipes_slub'), 'recipes', ['slub'], unique=True)
    op.drop_column('recipes', 'slug')
    # ### end Alembic commands ###
