"""add author lazy='selectin' to recipe model

Revision ID: 6a516e9a0d28
Revises: fc035efea24e
Create Date: 2026-02-13 23:48:24.793924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a516e9a0d28'
down_revision: Union[str, Sequence[str], None] = 'fc035efea24e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
