"""add slug field to recipe

Revision ID: f9d05eb47ce9
Revises: d79e2e85a532
Create Date: 2026-02-12 01:22:19.941337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9d05eb47ce9'
down_revision: Union[str, Sequence[str], None] = 'd79e2e85a532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('slub', sa.String(), nullable=False))
    op.create_index(op.f('ix_recipes_slub'), 'recipes', ['slub'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipes_slub'), table_name='recipes')
    op.drop_column('recipes', 'slub')
    # ### end Alembic commands ###
